language: elixir
dist: trusty
addons:
  chrome: stable
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - npm install && node_modules/brunch/bin/brunch build --production
  - mix compile
  - mix phx.digest
before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver

elixir:
  - 1.6.0
otp_release:
  - 20.0

env:
  - MIX_ENV=test

before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "nohup chromedriver &"

script:
  - mix test
  - mix dialyer

after_script:
  - cd $TRAVIS_BUILD_DIR
  - MIX_ENV=docs mix inch.report


