addons:
  chrome: stable
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: elixir
matrix:
  include:
    # - otp_release: 18.3
    #   elixir: 1.4
    - otp_release: 19.3
      elixir: 1.4
    # - otp_release: 20.0
    #   elixir: 1.4
# sudo: required
dist: trusty
env:
  - ELIXIR_ASSERT_TIMEOUT=2000
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # - chromedriver &
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  # - sleep 3
  - wget http://chromedriver.storage.googleapis.com/2.7/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo apt-get install libnss3
  - sudo apt-get --only-upgrade install google-chrome-stable
  - sudo cp chromedriver /usr/local/bin/
  - sudo chmod +x /usr/local/bin/chromedriver
  - /usr/local/bin/chromedriver &
  - mix deps.get
  - nvm install 6.2 && nvm use 6.2
script:
  - mix test
after_script:
  - cd $TRAVIS_BUILD_DIR
  - MIX_ENV=docs mix inch.report


